/**
 * LLM Provider — abstraction over execution backends.
 * Brain and workers both use this interface.
 */

/** Content block — supports multimodal input (text, image, file) */
export type ContentBlock =
  | { type: 'text'; text: string }
  | { type: 'image'; source: ImageSource }
  | { type: 'file'; path: string; mediaType?: string };

export interface ImageSource {
  /** 'base64' for inline, 'url' for remote */
  type: 'base64' | 'url';
  /** MIME type: image/png, image/jpeg, image/gif, image/webp */
  mediaType: string;
  /** base64 data or URL */
  data: string;
}

/** Prompt can be a simple string or multimodal content blocks */
export type Prompt = string | ContentBlock[];

/** Response can be text or structured multimodal output */
export interface StructuredResponse {
  text: string;
  /** Optional: files created/modified by the worker */
  files?: Array<{ path: string; mediaType?: string }>;
  /** Optional: images generated by the worker */
  images?: Array<{ mediaType: string; data: string }>;
  /** Optional: metadata (token usage, duration, model) */
  metadata?: Record<string, unknown>;
}

export interface LLMProvider {
  think(prompt: Prompt, systemPrompt: string): Promise<string>;
  /** Extended: return structured response with optional multimodal output */
  thinkStructured?(prompt: Prompt, systemPrompt: string): Promise<StructuredResponse>;
}
